// Generated by CoffeeScript 1.3.3
var Sound;

Sound = (function() {

  function Sound(src) {
    this.src = src;
    this.audio = new Audio(this.src);
  }

  Sound.prototype.play = (function() {
    if (window.chrome) {
      return function() {
        this.audio.load();
        return this.audio.play();
      };
    }
    return function() {
      return this.audio.play();
    };
  })();

  return Sound;

})();
